### ISSUE TITLE
Possible bug in ByteArrayMismatch benchmark

### ISSUE THREAD

**Issue by amCap1712** [richardstartin/simdbenchmarks#1]
The [ByteArrayMismatch](https://github.com/richardstartin/simdbenchmarks/blob/master/src/main/java/com/openkappa/simd/mismatch/ByteArrayMismatch.java) benchmark uses `BytePrefixData` for generating arrays with a common prefix to benchmark the implementations. The setup in `BytePrefixData` calls `createByteArray`. The seed in `createByteArray` is fixed to `0`. So every invocation of `createByteArray` always generates the same numbers in the same order.
https://github.com/richardstartin/simdbenchmarks/blob/36a6f27eb17a7f3b4fba91f2d287ecc29f2f2501/src/main/java/com/openkappa/simd/DataUtil.java#L75-L80

This seems suspicious because if it were intended then there wouldn't be a need for the code to set a common prefix.
https://github.com/richardstartin/simdbenchmarks/blob/36a6f27eb17a7f3b4fba91f2d287ecc29f2f2501/src/main/java/com/openkappa/simd/state/BytePrefixData.java#L25-L28

**Comment by richardstartin** [comment]
The reason for the seed is to create the same data for every invocation so invocations are comparable. The reason for setting the prefix is so the seed can be changed at the command line, rather than rely on seed dependent RNG behaviour. In other words, the benchmark works the same way with parameterised seeds.

**Comment by amCap1712** [comment]
Makes sense. Thanks for the explanation!
